### ISSUE TITLE
在发送原图哪里把false改成ture后会出现一个关于撤回时间的错误

### ISSUE THREAD

**Issue by sayri23** [bloodyrabbit/mirai-setu#14]
![IMG_20210506_201041](https://user-images.githubusercontent.com/62638560/117296109-40828880-aea7-11eb-9143-f395d402f961.jpg)

**Comment by bloodyrabbit** [comment]
注意一下yaml的格式比较严格,不要遗漏空格，最好使用vs code，vim这些编辑器修改。如果还是有问题请贴出setu-config的完整内容。

**Comment by bloodyrabbit** [comment]
还有是true不是ture
