### ISSUE TITLE
发送图片不显示图片信息

### ISSUE THREAD

**Issue by AnyMoonS** [bloodyrabbit/mirai-setu#18]
使用指令获取图片时只会发送图片
关于作者之类的信息无法发送
以及以图搜图时信息也无法发送（控制台已经有输出了，但群内没有）
但是切换模式等信息可以正常发送

**Comment by bloodyrabbit** [comment]
是新登录的账号吗？新登录的账号有时候会因为风控有些消息发送不出去。
一般等一个周之后会恢复

**Comment by AnYingYueShu** [comment]
> 是新登录的账号吗？新登录的账号有时候会因为风控有些消息发送不出去。
> 一般等一个周之后会恢复

是新登录的账号，那我再等等吧，感谢回复

**Comment by bloodyrabbit** [comment]
我考虑增加一个将文字转换成图片的功能，来作为等待风控期间的替代方法。#13[https://github.com/bloodyrabbit/mirai-setu/issues/11](url)
