### ISSUE TITLE
mirai2.0

### ISSUE THREAD

**Issue by wqy0916** [bloodyrabbit/mirai-setu#2]
在最新版上无法使用，请适配一下，谢谢 还有要是搜出来的图片要是可以同时保存在本地就好了

**Comment by bloodyrabbit** [comment]
在搞了，mirai2.0修改了很多的API。图片保存在本地我会考虑添加的

**Comment by bloodyrabbit** [comment]
简单适配了2.0版本，可以下载尝试了。下个版本我会加入保存到本地的功能

**Comment by wqy0916** [comment]
> 简单适配了2.0版本，可以下载尝试了。下个版本我会加入保存到本地的功能

谢谢
