### ISSUE TITLE
不能自动撤回了

### ISSUE THREAD

**Issue by tamako-1** [bloodyrabbit/mirai-setu#23]
将撤回时间设置成90000，经过相应时间也未撤回

**Comment by bloodyrabbit** [comment]
收到，抱歉最近在忙毕业论文，没有及时回复。

**Comment by tamako-1** [comment]
没关系，麻烦看一下是为什么，我开了代理
我换回旧版的就没有这个问题，感谢回复

**Comment by bloodyrabbit** [comment]
我看看，因为之前的代码有点混乱，这个版本进行了大量的整理，可能一些功能失效了

**Comment by bloodyrabbit** [comment]
撤回我测试没有问题，能在详细的描述一下吗

**Comment by tamako-1** [comment]
我再试试，看能不能复现

**Comment by tamako-1** [comment]
![QQ截图20210601183517](https://user-images.githubusercontent.com/81067588/120309839-46ce1e00-c308-11eb-9f9e-98cb37637587.png)
![A0F408EAB953247581F54B73719CC41A](https://user-images.githubusercontent.com/81067588/120309966-6c5b2780-c308-11eb-886f-d97cc877696d.jpg)
![QQ截图20210601183739](https://user-images.githubusercontent.com/81067588/120310090-91e83100-c308-11eb-8213-3f7e1ab879a2.png)
后台也没有报错

**Comment by bloodyrabbit** [comment]
可能我不小心修好了？
我现在的代码测试都是正常的，但是我印象中没有动那里的代码：D
