### ISSUE TITLE
1.2.0版本自动生成的setting中缺少useoriginalImage选项，但是该选项依旧可用

### ISSUE THREAD

**Issue by LemonPAKA** [bloodyrabbit/mirai-setu#25]
默认值为false。。。我说怎么PC看不到图了
需要手动添加useoriginalImage: true到设置文件中

**Comment by bloodyrabbit** [comment]
新版本我删除了获取缩略图的代码，也在配置文件中删除了这个。不该能用啊

**Comment by LemonPAKA** [comment]
那应该是有些图PC就加载不了，改成了另一项还是？
