### ISSUE TITLE
loliconapi

### ISSUE THREAD

**Issue by tamako-1** [bloodyrabbit/mirai-setu#26]
不知道为什么突然用不了了
![QQ截图20210606013039](https://user-images.githubusercontent.com/81067588/120900392-246d3500-c667-11eb-8a7b-7d205c4c5ccc.png)
![QQ图片20210606013155](https://user-images.githubusercontent.com/81067588/120900400-2afbac80-c667-11eb-9b59-17944652a83d.jpg)

**Comment by bloodyrabbit** [comment]
收到，我这里也批量的遇到了这个问题，在排查了

**Comment by bloodyrabbit** [comment]
lolicon解除了每日色图的限制，也不需要申请额外的apikey了，因为返回的数据格式也发生了变化所以我的插件现在不能进行解析了。
正在做适配和测试了

**Comment by tamako-1** [comment]
感谢大佬

**Comment by bloodyrabbit** [comment]
临时可以在配置文件修改使用fantasyzone的api

**Comment by bloodyrabbit** [comment]
已经上传新版本

**Comment by tamako-1** [comment]
可以了，谢谢

**Comment by tamako-1** [comment]
感觉又不能撤回了

**Comment by bloodyrabbit** [comment]
我明天看一下吧，十一点的时候我的bot账号被封了，等一天解封

**Comment by bloodyrabbit** [comment]
我这里尝试撤回功能都是正常的。
不过我觉得是先发出了图片信息，然后再发送图片，图片发送之后自动撤回才开始计时。有时候图片下载时间过场导致先发送的图片信息时间超过三分钟，无法撤回导致抛出错误，然后导致无法撤回。
我会修改成图片获取并且上传完成再发送信息
