### ISSUE TITLE
mcl启动出错

### ISSUE THREAD

**Issue by zhizicq** [bloodyrabbit/mirai-setu#3]
![新建位图图像](https://user-images.githubusercontent.com/26905327/104684092-33446100-5733-11eb-8214-643d3df742bb.png)
![新建位图图像](https://user-images.githubusercontent.com/26905327/104684167-5f5fe200-5733-11eb-99d7-ad51eec3a9ee.png)

使用mcl载入会出错，请问是什么原因？

**Comment by bloodyrabbit** [comment]
用的是哪个版本。mirai的核心是哪个版本。
猜测这个应该是mirai2.0用了1.0的插件的原因把

**Comment by bloodyrabbit** [comment]
问题解决了吗，没问题的话我先关闭了。有问题欢迎再提出
