### ISSUE TITLE
一直提示权限不足是为啥

### ISSUE THREAD

**Issue by guanyintu** [bloodyrabbit/mirai-setu#32]
我自己是拿到*：*的权限，而且还是群主但是一直提示我权限不足？？？

**Comment by bloodyrabbit** [comment]
在配置文件中修改权限模式了吗

**Comment by guanyintu** [comment]
![image](https://user-images.githubusercontent.com/37127965/123507573-cb5c5400-d69c-11eb-9f17-f6b8c6a7e89d.png)
是这个吗？

**Comment by bloodyrabbit** [comment]
不是这个，这个是存数据用的，config那里面配置权限模式

**Comment by guanyintu** [comment]
好的，那没事了
