### ISSUE TITLE
我这边帮忙把代码适配了V2。

### ISSUE THREAD

**Issue by Oeeder** [bloodyrabbit/mirai-setu#38]
最近刚刚入门，发现这个插件的代码比较简单入门易懂。
在经过一段时间的摸索后，我把插件的源代码从V1适配到了V2，不过目前我还不知道怎么进行多Tag进行搜图，不过API还是匹配到V2上了。
而且原来的1.2.2的以图搜图没有功能权限，我这边也增加上去了（我那群封印插件但是天天以图搜图玩）

如果作者同意的话，我这边可以发出来。

**Comment by Oeeder** [comment]
并且根据群友的意见，我这边直接把搜图的回复去除掉了，直接改为发图。
并且原来的代理设置好像有问题，走不了代理，只能从源代码里面改，虽然论坛的360滑稽有给过我建议，不过我有点懒，没有加上去。

**Comment by bloodyrabbit** [comment]
谢谢！
LoliconV2我已经在适配了，也是适配了多tag搜索，可以看 [1.3-dev](https://github.com/bloodyrabbit/mirai-setu/tree/1.3-dev) 的分支。
以图搜图的权限我觉得没啥必要添加，不是什么敏感功能，都可以用的。
不过我现在还是比较忙碌的，所以更新比较慢的（其实闲置时间都去玩游戏去了）。

**Comment by Oeeder** [comment]
主要还是，总有的时候能搜出黄图。以图搜图没有黄图识别。
我这今天已经逮到几个拿打码的图去搜步兵图的群友了。（草）
为了我机器人的安全着想，我这边加了权限。

**Comment by Oeeder** [comment]
如果有需要的话，我这边可以发我的代码出来供参考一下，只是拿你的代码稍微修改了一下，毕竟我才刚入门

**Comment by bloodyrabbit** [comment]
如果你觉得代码不错的话可以pr给我，你也可以上传到自己的仓库里我会去看一下的。
谢谢了

**Comment by Oeeder** [comment]
https://github.com/Oeeder/mirai-setu-for-bloodyrabbit
这边上传到仓库了。
因为刚入门，可能代码没有这么好看，以及方便测试，有很多注释或者日志发送的东西

**Comment by bloodyrabbit** [comment]
好的，看一下。
其实我也是新手，kotlin是做这个插件边学边做的。
