### ISSUE TITLE
当关键词取图用FantasyZoneapi时报错

### ISSUE THREAD

**Issue by ShengErWeiGe** [bloodyrabbit/mirai-setu#41]
PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
报证书错误，是api的问题吗？

**Comment by bloodyrabbit** [comment]
测试了一下我这里还是没问题的。有没有更多的细节。
可以尝试更新一下java的版本，以前遇到一个问题用老版本的java会导致证书错误

**Comment by ShengErWeiGe** [comment]
你好，已经解决了，是java版本的问题
