### ISSUE TITLE
检测到敏感资源拒绝发送

### ISSUE THREAD

**Issue by RoundLun** [bloodyrabbit/mirai-setu#5]
检测到敏感资源拒绝发送该怎么办呢，只能一直等么

**Comment by bloodyrabbit** [comment]
这个是有时候搜到了r-18的资源给我拦截掉了。因为有一定概率封号的。
如果你想看插件配置有个r18的选项改成true就不会拦截掉了。

**Comment by bloodyrabbit** [comment]
我在新版本修改了这个机制，可以试一试
