### ISSUE TITLE
PCQQ图片接收不到

### ISSUE THREAD

**Issue by wqy0916** [bloodyrabbit/mirai-setu#6]
这次的0.2.3版本使用后我发现PCQQ收不到图片了，上一个版本还行，发图的速度是快了不少真不错
![image](https://user-images.githubusercontent.com/38550132/108277961-3957b280-71b5-11eb-9ed8-4b58cb5a660a.png)
mirai使用的版本为2.4.0,希望能修复一下

**Comment by bloodyrabbit** [comment]
这个bug挺奇怪的，发送图片我修改成了获取图片的预览图来减少下载需要的时间，然后才出现了pc端不显示图片，手机端图片也无法转发的bug，获取原始大图发送就没有什么问题。
我先增加个只发送原始图片的方案作为临时方案，图片无法发送具体是因为什么我再琢磨琢磨

**Comment by bloodyrabbit** [comment]
已经上传了新版本

**Comment by wqy0916** [comment]
> 已经上传了新版本

辛苦啦
