### ISSUE TITLE
设置master会报错

### ISSUE THREAD

**Issue by qingfengnya** [bloodyrabbit/mirai-setu#8]
![IMG_20210306_122612](https://user-images.githubusercontent.com/80141560/110195111-2f9da280-7e77-11eb-8e31-5ca3155c6b30.png)

**Comment by bloodyrabbit** [comment]
注意yaml的格式，引号后面是有空格的。
使用vscode之类的专业文本编辑器。记事本有时候会出现莫名奇妙的不可见字符
