### ISSUE TITLE
一直提示您没有权限进行此操作

### ISSUE THREAD

**Issue by mojizooo** [bloodyrabbit/mirai-setu#9]
![MP{J`USQ}XOY5L4FQ~1JIS](https://user-images.githubusercontent.com/82160301/114034388-b992be00-98b0-11eb-9419-b40fcb24e288.png)
![XDS2O WF8WQ$0QHFY6OX_6](https://user-images.githubusercontent.com/82160301/114034502-d16a4200-98b0-11eb-8bf9-5863aa9df772.png)

**Comment by bloodyrabbit** [comment]
这个是配置mirai命令权限的，不是插件的权限。
配置这个需要在配置文件填写。
config/Mirai-setu/setu-config
![image](https://user-images.githubusercontent.com/41462933/114035078-5ce3d300-98b1-11eb-87c7-7dc9e18c75fc.png)

**Comment by mojizooo** [comment]
okkkkkkkk 这个插件目前是只能管理或者指定人更改对吗

**Comment by bloodyrabbit** [comment]
是的，目前只能指定人和管理和控制。
如果有什么需要你也可以提出来，我可以后期更新。

**Comment by mojizooo** [comment]
回的好快诶 阿里嘎多阿里嘎多
